### ISSUE TITLE
🐛 [BUG] When the port is occupied, `swanlab watch` does not prompt an error.

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#100] opened 2023-12-28 20:24 UTC
## 🐛 Bug description [Please make everyone to understand it]

When the port of `swanlab watch` is occupied, the process is terminated directly without displaying any error message.

![image](https://github.com/SwanHubX/SwanLab/assets/58305964/1ed880dc-0e6a-47bb-a589-d5aef407cbe1)

## 🧑‍💻 Step to reproduce

Open `swanlab watch` on two terminals.

## 👾 Expected result

When detected occupation, give the user a prompt message.

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.1.1

- **Platform**: MacOS M1Max

**Comment by SAKURA-CAT** [comment] 2023-12-29 05:47
This issue is a duplicate of #81. By the way, we are in the process of identifying the related errors. Please be patient while we investigate.

**Closed** 2024-01-03 07:44 UTC
Labels: bug, duplicate
