### ISSUE TITLE
🐛 [BUG] fsspec uninstall error when install swanlab using pip on pytorch env

### ISSUE THREAD

**Issue by defineHong** [SwanHubX/SwanLab#71] opened 2023-12-23 09:27 UTC
## 🐛 Bug description

In a conda environment that includes PyTorch, I encountered the following error when attempting to install swanlab using pip: "torch 2.1.2 requires fsspec, which is not installed." It's worth noting that this error isn't caused by the installation of PyTorch itself. I tried installing other packages like tqdm after installing PyTorch, and there were no errors. However, this specific error only occurred after I attempted to install swanlab.

<img width="1097" alt="Screenshot 2023-12-23 at 17 06 52" src="https://github.com/SwanHubX/SwanLab/assets/35194781/288b22a8-0768-49f4-bfbd-f1a818727b18">

## 🧑‍💻 Step to reproduce

First, create a new Conda environment in Ubuntu 22.04, specifying Python version 3.11, and install PyTorch version 2.1.2 following the official PyTorch [installation tutorial](https://pytorch.org/get-started/locally/).

Next, install tqdm(for test) using command: pip install tqdm. It appears that the installation was successful, and there were no error messages.

<img width="632" alt="Screenshot 2023-12-23 at 17 18 59" src="https://github.com/SwanHubX/SwanLab/assets/35194781/84f4bbb9-6f73-41ae-85b4-1981acd46b13">

Finally, when using the `pip install swanlab` command to install swanlab, an error message appeared stating "torch 2.1.2 requires fsspec, which is not installed." Additionally, the log indicated that the version of typing_extensions had been changed at some point.

The error can be fix by using the command "pip install fsspec."

## 🤔️Analysis

I checked the logs, and it seems that the issue may be related to the version of typing_extensions. After installing torch 2.1.2, the environment will contain typing_extensions version 4.7.1, which appears to be a dependency of torch 2.1.2. However, when installing swanlab, typing_extensions is replaced with version 4.9.0. This could potentially be the cause of the problem.

Furthermore, when I use the "pip install typing_extensions==4.7.1" command to forcefully install version 4.7.1 of typing_extensions, an error message tells me that fastapi version 0.105.0 requires typing_extensions version 4.8.0 or higher, and fastapi is a package that swanlab depends on.

<img width="1090" alt="Screenshot 2023-12-23 at 17 24 43" src="https://github.com/SwanHubX/SwanLab/assets/35194781/ee015a7d-87a8-42a0-864e-b73aca55f1c1">

**Comment by SAKURA-CAT** [comment] 2023-12-23 10:33
Thanks for the feedback, we will try to fix this in the next release.

**Comment by SAKURA-CAT** [comment] 2023-12-26 13:46
Sorry, due to the update of Cui Xun and some of my own reasons, I can't reproduce and fix this problem in version v0.1.1. Please look forward to the next version!
🧎🧎🧎🧎🧎🧎🧎🧎🧎

**Comment by defineHong** [comment] 2023-12-26 16:41
thanks for your job! let`s waiting for update.

**Comment by xiaolin199912** [comment] 2023-12-26 18:44
I have tested the installation of `torch==2.1.2` and `swanlab==0.1.1` in conda environments with `python3.10` and `python3.11`, and it seems that no relevant errors were encountered.

**Comment by Feudalman** [comment] 2023-12-28 13:08
I try to reproduce, but failed.
There are no errors and the version of fsspec is 4.9.0

**Comment by SAKURA-CAT** [comment] 2023-12-30 16:13
marked as not planned

**Closed by SAKURA-CAT** 2023-12-30 16:13 UTC
Labels: bug
